### ISSUE TITLE
Need guidance on using java-spotify-api as a basic player.

### ISSUE THREAD

**Issue by kRystalDevv** [LabyStudio/java-spotify-api#11]
I am relatively new to the Spotify API and am currently attempting to integrate it into my project as a basic player. Despite reviewing the documentation, I find myself unclear on the essential steps and requirements.

I have a few specific queries regarding the integration process:
1. How do I establish a connection and link my application API with the Spotify API?
2. I currently have three buttons to control playback in my GUI-based project developed with Ant.

Development Environment:
- IDE: NetBeans 17
- Java Version: 21
- Build System: Ant

If any additional information is needed to better understand my situation, Please ask, I'll provide it.

**Comment by LabyStudio** [comment]
Be aware that this API only accesses the Spotify application locally and uses an unofficial method.
The playback control simply accesses the media API of your operating system to change or play/pause songs.
If you want to control playback with the API, you can simply call:
```java
SpotifyAPI api = SpotifyAPIFactory.createInitialized();

// Send media keys to the operating system
api.pressMediaKey(MediaKey.PLAY_PAUSE);
api.pressMediaKey(MediaKey.PREV);
api.pressMediaKey(MediaKey.NEXT);
```

If you want to read the current state of the Spotify player you can use the example of the README file.
Depending on the operating system, different methods are used to access the data.
Under Linux, the data is read from dbus-send, under macOS AppleScript is used and under Windows the data is read from memory.

**Comment by kRystalDevv** [comment]
thanks for giving a clearer understanding!
