### ISSUE TITLE
Recent Spotify update broke the API

### ISSUE THREAD

**Issue by NULLYUKI** [LabyStudio/java-spotify-api#5]
Apparently since the latest Spotify update, the API seems broken and does not work properly anymore.
I'm not getting any errors inside of LabyMod.

So I'm currently trying to get in contact with @PrincessAkira again to help out investigating, so we can maybe find the error, the reason for the error and then provide a fix for it in form as a PR.

Tested with Spotify version:
Spotify für Windows (64 Bit)
1.2.20.1216.ge7a7b92f

**Comment by HerXayah** [comment]
Works for me idk 🤷🏻 
Maybe app changed size of dll?
Looking into it rn

**Comment by NULLYUKI** [comment]
> Works for me idk 🤷🏻 Maybe app changed size of dll?

Huh.
There have been some recent reports on the LabyMod Discord that after updating Spotify, the addon stopped working.
I also installed Spotify from the official website and used the latest Snapshot version in the LabyMod Launcher with 1.20.1 and it didn't worked.

**Comment by HerXayah** [comment]
> > Works for me idk 🤷🏻 Maybe app changed size of dll?
> 
> Huh. There have been some recent reports on the LabyMod Discord that after updating Spotify, the addon stopped working. I also installed Spotify from the official website and used the latest Snapshot version in the LabyMod Launcher with 1.20.1 and it didn't worked.

Enable Disable Addon. Easy fix.

**Comment by NULLYUKI** [comment]
> > > Works for me idk 🤷🏻 Maybe app changed size of dll?
> > 
> > 
> > Huh. There have been some recent reports on the LabyMod Discord that after updating Spotify, the addon stopped working. I also installed Spotify from the official website and used the latest Snapshot version in the LabyMod Launcher with 1.20.1 and it didn't worked.
> 
> Enable Disable Addon. Easy fix.

What? A more detailed description would be neat xd I don't understand what you mean by that.

**Comment by HerXayah** [comment]
It doesnt work on latest 64-Bit. I already fixed it though.
Commiting soon

EDIT:
Nevermind.
The offset is stil the same. It worked for a split second. weird...

EDIT 2: nvm im stupid.

**Comment by NULLYUKI** [comment]
Sounds interesting how it is going right now xd Kinda annoying that it broke shortly after we implemented 32Bit support.
Keep us updated, Thank you!

**Comment by HerXayah** [comment]
New Offsets are in #6

**Comment by NULLYUKI** [comment]
> New Offsets are in #6

Ah a easy and quick fix. Nice! Good Job! Now lets hope this will be quickly merged.

**Comment by NULLYUKI** [comment]
After reading through https://github.com/LabyStudio/java-spotify-api/pull/6#issuecomment-1724246032 

It looks like that the new Spotify update broke more things than expected. So it might take a bit more time until everything is fixed and can be merged.

**Comment by LabyStudio** [comment]
I'm not sure if the new playback offsets work globally on all computers, but it works for me.
Maybe we need a similar approach to the playback like the 32/64 offsets.

I released the current version for now.

**Comment by NULLYUKI** [comment]
> I'm not sure if the new playback offsets work globally on all computers, but it works for me. Maybe we need a similar approach to the playback like the 32/64 offsets.
> 
> I released the current version for now.

Yeah in case we will find something regarding this, we will make sure to create a new issue and PR.
