### ISSUE TITLE
Recent Spotify update broke the API (again)

### ISSUE THREAD

**Issue by NULLYUKI** [LabyStudio/java-spotify-api#7]
Apparently since the latest Spotify update (again), the API seems broken and does not work properly anymore.
I'm not getting any errors inside of LabyMod.

I sent @PrincessAkira a message about this, so that a fix will be worked on.

Tested with Spotify version:
Spotify für Windows (64 Bit)
1.2.21.1104.g42cf0a50

**Comment by NULLYUKI** [comment]
Depending on what the issue might be, I would suggest that we start to find and work on a solution, that will automatically scan for changed memory addresses on start.

As we know what things are holding onto these memory addresses, we can probably scan them and automatically apply them if they have changed.

Theoretical this should be possible and work, but we would have to figure out first on how to do it, and if its permanently working in case a Spotify update is changing stuff again that would break the API.

**Update**
Fix is done now and can be find at #8

**Comment by LabyStudio** [comment]
I added scanning as a fallback now. Let's hope it works for a while now

**Comment by NULLYUKI** [comment]
> I added scanning as a fallback now. Let's hope it works for a while now

Yes, that should probably work. In case something would break, I will also try to look if there is a way to improve the scan as a fallback.
